export const EVENT_LIST_REQUEST = "event/EVENT_LIST_REQUEST";
export const EVENT_LIST_SUCCESS = "event/EVENT_LIST_SUCCESS";
export const EVENT_LIST_FAIL = "event/EVENT_LIST_FAIL";

export const AUTH_EVENT_LIST_REQUEST = "event/AUTH_EVENT_LIST_REQUEST";
export const AUTH_EVENT_LIST_SUCCESS = "event/AUTH_EVENT_LIST_SUCCESS";
export const AUTH_EVENT_LIST_FAIL = "event/AUTH_EVENT_LIST_FAIL";

export const EVENT_DETAILS_REQUEST = "event/EVENT_DETAILS_REQUEST";
export const EVENT_DETAILS_SUCCESS = "event/EVENT_DETAILS_SUCCESS";
export const EVENT_DETAILS_FAIL = "event/EVENT_DETAILS_FAIL";

export const AUTHOR_EVENT_LIST_REQUEST = "event/AUTHOR_EVENT_LIST_REQUEST";
export const AUTHOR_EVENT_LIST_SUCCESS = "event/AUTHOR_EVENT_LIST_SUCCESS";
export const AUTHOR_EVENT_LIST_FAIL = "event/AUTHOR_EVENT_LIST_FAIL";

export const MYEVENT_LIST_REQUEST = "event/MYEVENT_LIST_REQUEST";
export const MYEVENT_LIST_SUCCESS = "event/MYEVENT_LIST_SUCCESS";
export const MYEVENT_LIST_FAIL = "event/MYEVENT_LIST_FAIL";

export const EVENT_UPDATE_REQUEST = "event/EVENT_UPDATE_REQUEST";
export const EVENT_UPDATE_SUCCESS = "event/EVENT_UPDATE_SUCCESS";
export const EVENT_UPDATE_FAIL = "event/EVENT_UPDATE_FAIL";

export const EVENT_DELETE_REQUEST = "event/EVENT_DELETE_REQUEST";
export const EVENT_DELETE_SUCCESS = "event/EVENT_DELETE_SUCCESS";
export const EVENT_DELETE_FAIL = "event/EVENT_DELETE_FAIL";

export const EVENT_ACTION_REQUEST = "event/EVENT_ACTION_REQUEST";
export const EVENT_ACTION_SUCCESS = "event/EVENT_ACTION_SUCCESS";
export const EVENT_ACTION_FAIL = "event/EVENT_ACTION_FAIL";

export const EVENT_OPINION_CREATE_REQUEST =
  "event/EVENT_OPINION_CREATE_REQUEST";
export const EVENT_OPINION_CREATE_SUCCESS =
  "event/EVENT_OPINION_CREATE_SUCCESS";
export const EVENT_OPINION_CREATE_FAIL = "event/EVENT_OPINION_CREATE_FAIL";

export const EVENT_OPINION_DELETE_REQUEST =
  "event/EVENT_OPINION_DELETE_REQUEST";
export const EVENT_OPINION_DELETE_SUCCESS =
  "event/EVENT_OPINION_DELETE_SUCCESS";
export const EVENT_OPINION_DELETE_FAIL = "event/EVENT_OPINION_DELETE_FAIL";

export const EVENT_OPINION_EDIT_REQUEST = "event/EVENT_OPINION_EDIT_REQUEST";
export const EVENT_OPINION_EDIT_SUCCESS = "event/EVENT_OPINION_EDIT_SUCCESS";
export const EVENT_OPINION_EDIT_FAIL = "event/EVENT_OPINION_EDIT_FAIL";
