export const USER_LOGIN_REQUEST = "user/USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "user/USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "user/USER_LOGIN_FAIL";

export const USER_LOGOUT = "user/USER_LOGOUT";

export const USER_REGISTER_REQUEST = "user/USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "user/USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "user/USER_REGISTER_FAIL";

export const USER_PROFILE_DETAILS_REQUEST = "user/USER_PROFILE_DETAILS_REQUEST";
export const USER_PROFILE_DETAILS_SUCCESS = "user/USER_PROFILE_DETAILS_SUCCESS";
export const USER_PROFILE_DETAILS_FAIL = "user/USER_PROFILE_DETAILS_FAIL";
export const USER_PROFILE_DETAILS_RESET = "user/USER_PROFILE_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "user/USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "user/USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "user/USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "user/USER_UPDATE_PROFILE_RESET";
